version: '3'
services:
  apple-health-aggregate:
    build: .
    container_name: apple-health-aggregate
    environment:
      - PASSWORD=MY_PASSWORD
    ports:
      - 8787:8787
    volumes:
      - .:/home/rstudio
    tty: true
    stdin_open: true
